<?php
if( function_exists('acf_add_local_field_group') ):
    
    acf_add_local_field_group(array (
        'key' => 'group_5a16e33ac7a01',
        'title' => 'Membership Options',
        'fields' => array (
            array (
                'key' => 'field_5a16e347bac76',
                'label' => 'Membership Plan',
                'name' => 'membership_plan',
                'type' => 'repeater',
                'value' => NULL,
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Plan',
                'sub_fields' => array (
                    array (
                        'key' => 'field_5a16e398bac77',
                        'label' => 'Plan',
                        'name' => 'plan',
                        'type' => 'group',
                        'value' => NULL,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_5a16e3aabac78',
                                'label' => 'Short Title',
                                'name' => 'short_title',
                                'type' => 'text',
                                'value' => NULL,
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '100',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_5a16e3d8bac79',
                                'label' => 'Title',
                                'name' => 'title',
                                'type' => 'text',
                                'value' => NULL,
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '100',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_5a16e36b4040a',
                                'label' => 'Plan Image',
                                'name' => 'plan_image',
                                'type' => 'image',
                                'value' => NULL,
                                'instructions' => 'Select or upload an image to represent this membership plan. Dimensions: base images should be 386px x 218px while the middle image should be 386px x 240px.',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '100',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'url',
                                'preview_size' => 'medium',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                            array (
                                'key' => 'field_5a16e3e4bac7a',
                                'label' => 'Title Description',
                                'name' => 'title_description',
                                'type' => 'text',
                                'value' => NULL,
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '100',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_5a16e40abac7b',
                                'label' => 'Price',
                                'name' => 'price',
                                'type' => 'text',
                                'value' => NULL,
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '100',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_5a16e43ebac7c',
                                'label' => 'Price Description',
                                'name' => 'price_description',
                                'type' => 'text',
                                'value' => NULL,
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '100',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_5a16e44abac7d',
                                'label' => 'Features',
                                'name' => 'features',
                                'type' => 'repeater',
                                'value' => NULL,
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'table',
                                'button_label' => 'Add Feature',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_5a16e460bac7e',
                                        'label' => 'Feature',
                                        'name' => 'feature',
                                        'type' => 'text',
                                        'value' => NULL,
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '100',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                ),
                            ),
                            array (
                                'key' => 'field_5a16e47dbac7f',
                                'label' => 'Title Rate',
                                'name' => 'title_rate',
                                'type' => 'text',
                                'value' => NULL,
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_5a16e497bac80',
                                'label' => 'Rates',
                                'name' => 'rates',
                                'type' => 'repeater',
                                'value' => NULL,
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'block',
                                'button_label' => 'Add Rate',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_5a16e4aebac81',
                                        'label' => 'Vibe Rate',
                                        'name' => 'vibe_rate',
                                        'type' => 'text',
                                        'value' => NULL,
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '100',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                ),
                            ),
                            array (
                                'key' => 'field_5a16e4c5bac82',
                                'label' => 'Button Link',
                                'name' => 'button_link',
                                'type' => 'text',
                                'value' => NULL,
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_5a16e4d1bac83',
                                'label' => 'Button Text',
                                'name' => 'button_text',
                                'type' => 'text',
                                'value' => NULL,
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_5a16e4efbac84',
                                'label' => 'Button Target',
                                'name' => 'button_target',
                                'type' => 'select',
                                'value' => NULL,
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array (
                                    '_self' => 'Self',
                                    '_blank' => 'Blank',
                                ),
                                'default_value' => array (
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 0,
                                'ajax' => 0,
                                'return_format' => 'value',
                                'placeholder' => '',
                            ),
                            array (
                                'key' => 'field_5a16e50abac85',
                                'label' => 'Button Color',
                                'name' => 'button_color',
                                'type' => 'select',
                                'value' => NULL,
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array (
                                    'black' => 'Black',
                                    'orange' => 'Orange',
                                ),
                                'default_value' => array (
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 0,
                                'ajax' => 0,
                                'return_format' => 'value',
                                'placeholder' => '',
                            ),
                            array (
                                'key' => 'field_5a16e541bac86',
                                'label' => 'Plan Description',
                                'name' => 'plan_description',
                                'type' => 'wysiwyg',
                                'value' => NULL,
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '100',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                                'delay' => 0,
                            ),
                            array (
                                'key' => 'field_5a16e54ebac87',
                                'label' => 'Plan Background Color',
                                'name' => 'plan_color',
                                'type' => 'color_picker',
                                'value' => NULL,
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                            ),
                            array (
                                'key' => 'field_5a16e56cbac88',
                                'label' => 'Best Plan',
                                'name' => 'best_plan',
                                'type' => 'checkbox',
                                'value' => NULL,
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '30',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array (
                                    'yes' => 'Yes',
                                ),
                                'allow_custom' => 0,
                                'save_custom' => 0,
                                'default_value' => array (
                                ),
                                'layout' => 'vertical',
                                'toggle' => 0,
                                'return_format' => 'value',
                            ),
                        ),
                    ),
                ),
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-membership',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));
    
    endif;